GET http://localhost:3000/

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "role": "customer",
    "name": "David Thompson",
    "address": "456 Maple Rd, Bayside",
    "bio": "Cycling lover and mountain hiker",
    "email": "david.thompson451161@example.com",
    "phone": "5559012311415",
    "username": "davidthompson141516",
    "password": "davidsecure456"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "levanc",
  "password": "mypassword"
}